package com.cds.iot.data.source.local.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cds.iot.data.entity.SMessage;

import com.cds.iot.data.source.local.greendao.SMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sMessageDaoConfig;

    private final SMessageDao sMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sMessageDaoConfig = daoConfigMap.get(SMessageDao.class).clone();
        sMessageDaoConfig.initIdentityScope(type);

        sMessageDao = new SMessageDao(sMessageDaoConfig, this);

        registerDao(SMessage.class, sMessageDao);
    }
    
    public void clear() {
        sMessageDaoConfig.clearIdentityScope();
    }

    public SMessageDao getSMessageDao() {
        return sMessageDao;
    }

}
