package com.cds.iot.data.source.local.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.cds.iot.data.entity.SMessage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SMESSAGE".
*/
public class SMessageDao extends AbstractDao<SMessage, Long> {

    public static final String TABLENAME = "SMESSAGE";

    /**
     * Properties of entity SMessage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Token = new Property(1, String.class, "token", false, "TOKEN");
        public final static Property UserId = new Property(2, String.class, "userId", false, "USER_ID");
        public final static Property Uid = new Property(3, String.class, "uid", false, "UID");
        public final static Property MsgId = new Property(4, String.class, "msgId", false, "MSG_ID");
        public final static Property MsgType = new Property(5, String.class, "msgType", false, "MSG_TYPE");
        public final static Property Title = new Property(6, String.class, "title", false, "TITLE");
        public final static Property Content = new Property(7, String.class, "content", false, "CONTENT");
        public final static Property DeviceImg = new Property(8, String.class, "deviceImg", false, "DEVICE_IMG");
        public final static Property DeviceId = new Property(9, String.class, "deviceId", false, "DEVICE_ID");
        public final static Property DeviceName = new Property(10, String.class, "deviceName", false, "DEVICE_NAME");
        public final static Property DeviceType = new Property(11, String.class, "deviceType", false, "DEVICE_TYPE");
        public final static Property DeviceTypeName = new Property(12, String.class, "deviceTypeName", false, "DEVICE_TYPE_NAME");
        public final static Property PhotoUrl = new Property(13, String.class, "photoUrl", false, "PHOTO_URL");
        public final static Property VideoUrl = new Property(14, String.class, "videoUrl", false, "VIDEO_URL");
        public final static Property Tailtime = new Property(15, String.class, "tailtime", false, "TAILTIME");
    }


    public SMessageDao(DaoConfig config) {
        super(config);
    }
    
    public SMessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SMESSAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TOKEN\" TEXT," + // 1: token
                "\"USER_ID\" TEXT," + // 2: userId
                "\"UID\" TEXT," + // 3: uid
                "\"MSG_ID\" TEXT," + // 4: msgId
                "\"MSG_TYPE\" TEXT," + // 5: msgType
                "\"TITLE\" TEXT," + // 6: title
                "\"CONTENT\" TEXT," + // 7: content
                "\"DEVICE_IMG\" TEXT," + // 8: deviceImg
                "\"DEVICE_ID\" TEXT," + // 9: deviceId
                "\"DEVICE_NAME\" TEXT," + // 10: deviceName
                "\"DEVICE_TYPE\" TEXT," + // 11: deviceType
                "\"DEVICE_TYPE_NAME\" TEXT," + // 12: deviceTypeName
                "\"PHOTO_URL\" TEXT," + // 13: photoUrl
                "\"VIDEO_URL\" TEXT," + // 14: videoUrl
                "\"TAILTIME\" TEXT);"); // 15: tailtime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SMESSAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SMessage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String token = entity.getToken();
        if (token != null) {
            stmt.bindString(2, token);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(3, userId);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(4, uid);
        }
 
        String msgId = entity.getMsgId();
        if (msgId != null) {
            stmt.bindString(5, msgId);
        }
 
        String msgType = entity.getMsgType();
        if (msgType != null) {
            stmt.bindString(6, msgType);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(7, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(8, content);
        }
 
        String deviceImg = entity.getDeviceImg();
        if (deviceImg != null) {
            stmt.bindString(9, deviceImg);
        }
 
        String deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindString(10, deviceId);
        }
 
        String deviceName = entity.getDeviceName();
        if (deviceName != null) {
            stmt.bindString(11, deviceName);
        }
 
        String deviceType = entity.getDeviceType();
        if (deviceType != null) {
            stmt.bindString(12, deviceType);
        }
 
        String deviceTypeName = entity.getDeviceTypeName();
        if (deviceTypeName != null) {
            stmt.bindString(13, deviceTypeName);
        }
 
        String photoUrl = entity.getPhotoUrl();
        if (photoUrl != null) {
            stmt.bindString(14, photoUrl);
        }
 
        String videoUrl = entity.getVideoUrl();
        if (videoUrl != null) {
            stmt.bindString(15, videoUrl);
        }
 
        String tailtime = entity.getTailtime();
        if (tailtime != null) {
            stmt.bindString(16, tailtime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SMessage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String token = entity.getToken();
        if (token != null) {
            stmt.bindString(2, token);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(3, userId);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(4, uid);
        }
 
        String msgId = entity.getMsgId();
        if (msgId != null) {
            stmt.bindString(5, msgId);
        }
 
        String msgType = entity.getMsgType();
        if (msgType != null) {
            stmt.bindString(6, msgType);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(7, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(8, content);
        }
 
        String deviceImg = entity.getDeviceImg();
        if (deviceImg != null) {
            stmt.bindString(9, deviceImg);
        }
 
        String deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindString(10, deviceId);
        }
 
        String deviceName = entity.getDeviceName();
        if (deviceName != null) {
            stmt.bindString(11, deviceName);
        }
 
        String deviceType = entity.getDeviceType();
        if (deviceType != null) {
            stmt.bindString(12, deviceType);
        }
 
        String deviceTypeName = entity.getDeviceTypeName();
        if (deviceTypeName != null) {
            stmt.bindString(13, deviceTypeName);
        }
 
        String photoUrl = entity.getPhotoUrl();
        if (photoUrl != null) {
            stmt.bindString(14, photoUrl);
        }
 
        String videoUrl = entity.getVideoUrl();
        if (videoUrl != null) {
            stmt.bindString(15, videoUrl);
        }
 
        String tailtime = entity.getTailtime();
        if (tailtime != null) {
            stmt.bindString(16, tailtime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SMessage readEntity(Cursor cursor, int offset) {
        SMessage entity = new SMessage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // token
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // userId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // uid
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // msgId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // msgType
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // title
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // content
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // deviceImg
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // deviceId
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // deviceName
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // deviceType
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // deviceTypeName
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // photoUrl
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // videoUrl
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15) // tailtime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SMessage entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setToken(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUid(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMsgId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMsgType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTitle(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setContent(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setDeviceImg(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setDeviceId(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setDeviceName(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setDeviceType(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setDeviceTypeName(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setPhotoUrl(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setVideoUrl(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setTailtime(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SMessage entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SMessage entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SMessage entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
